### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by cps80** [jcdubron/scnn_pytorch#14]
/bin/sh: 1: ./tools/evaluate: Permission denied
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    test(model, device, test_loader, args, idx)
  File "/home/disk/chengpeisong/project/scnn_pytorch/python/test.py", line 49, in test
    args.test_data_dir, args.test_data_dir, args.test_list_file[list_idx]), shell=True)
  File "/home/chengpeisong/anaconda3/envs/pysot/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/chengpeisong/anaconda3/envs/pysot/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './tools/evaluate -a /home/disk/chengpeisong/project/SCNN/data/CULane -d ./output/lines/ -i /home/disk/chengpeisong/project/SCNN/data/CULane -l /home/disk/chengpeisong/project/SCNN/data/CULane/list/test.txt -w 30 -t 0.5 -c 1640 -r 590 -f 1' returned non-zero exit status 126.

Please help me! 
Thanks a lot!

**Comment by jcdubron** [comment]
```
chmod +x evaluate
./tools/evaluate
```

**Comment by cps80** [comment]
Thank you very much, I have solved the problem.
